from sqlalchemy import Column, Integer, String, Date, Time, DateTime, Boolean, Text, Float, ForeignKey
from .database import Base

class Ocorrencia(Base):
    __tablename__ = "ocorrencia"

    id = Column(Integer, primary_key=True, index=True)
    data_ocorrencia = Column(Date)
    hora_ocorrencia = Column(Time)
    situacao_ocorrencia_id = Column(Integer)
    tipo_atendimento_id = Column(Integer)
    programa_id = Column(Integer)
    tipo_ocorrencia_id = Column(Integer)
    protocolo = Column(String(20))
    regiao_id = Column(Integer)
    sigilo = Column(String(1))
    nome_completo = Column(String(150))
    endereco = Column(String(255))
    fone1 = Column(String(15))
    fone2 = Column(String(15))
    email = Column(String(100))
    url_file = Column(String(255))
    assunto = Column(String(255))
    mensagem = Column(Text)
    encaminhamento_orgao_id = Column(Integer)
    encaminhamento_usuario_id = Column(Integer, nullable=True)
    encaminhamento_data = Column(DateTime, nullable=True)
    parecer_usuario_id = Column(Integer)
    parecer_descricao = Column(Text)
    parecer_data = Column(DateTime, nullable=True)
    notificar = Column(String(1))
    notificado = Column(String(1))
    situacao_anterior = Column(Integer)
    programa_anterior = Column(Integer)
    tipo_atend_anterior = Column(Integer)
    pessoa_id = Column(Integer, nullable=True)
    user_id = Column(Integer, nullable=True)
    cadastro = Column(DateTime)
    atualizacao = Column(DateTime)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    arquivado = Column(String(1))
